SOURCE_ANTISEMITIC_TWEETS_TOPIC = "raw_tweets_antisemitic"
SOURCE_NOT_ANTISEMITIC_TWEETS_TOPIC = "raw_tweets_not_antisemitic"

DESTINATION_ANTISEMITIC_TWEETS_TOPIC = "preprocessed_tweets_antisemitic"
DESTINATION_NOT_ANTISEMITIC_TWEETS_TOPIC = "preprocessed_tweets_not_antisemitic"
